Repository milieuinfo/webcomponent-vl-ui-select, pull requests merged in 2019-09, with the labels that each got.

#21 UIG-218
  vl-select.src.js
Labels: maintenance

#22 Update link naar demo
  vl-select.src.js
Labels: maintenance

#29 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#11 Update dependency sinon to v7.4.1
  package-lock.json
  package.json
Labels: dependencies, renovate

#10 Update dependency replace to v1.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#9 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#35 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#34 Update dependency sinon to v7.4.2
  package-lock.json
  package.json
Labels: dependencies

#33 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#32 Update dependency @govflanders/vl-ui-util to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#31 Update dependency @govflanders/vl-ui-input-field to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#30 Update dependency @govflanders/vl-ui-core to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#36 Revert naar @govflanders 3.7.2
  package-lock.json
  package.json
Labels: bug

#37 Update dependency vl-ui-core to v1.4.7
  package-lock.json
  package.json
Labels: dependencies

#41 Automatic commit via update script
  demo/demo.css
  package-lock.json
  style.css
Labels: maintenance

#43 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance

#46 Update vl-ui-util
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  CODEOWNERS
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance

#47 Update dependency sinon to v7.5.0
  package-lock.json
  package.json
Labels: dependencies
