Repository milieuinfo/webcomponent-vl-ui-select, pull requests merged in 2019-10, with the labels that each got.

#49 #48 pas define aanroepen wanneer webcomponent volledig geladen is
  demo/vl-select.html
  package-lock.json
  package.json
  style.css
  test/vl-select.test.html
  vl-select.src.js
Labels: chore

#51 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance

#56 Rendering z-index probleem in combinatie met vl-upload
  demo/vl-select.html
  package-lock.json
  package.json
  style.css
  style.scss
Labels: bug

#58 Update README.md
  README.md
  package-lock.json
  package.json
Labels: maintenance

#59 Update README.md
  README.md
  package-lock.json
  package.json
Labels: maintenance
