Repository milieuinfo/webcomponent-vl-ui-select, pull requests merged in 2020-08, with the labels that each got.

#122 Update dependency @govflanders/vl-ui-input-field to v3.11.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#123 Update dependency @govflanders/vl-ui-select to v3.11.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#124 Update dependency @govflanders/vl-ui-util to v3.11.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#127 Upgrade huisstijl versie 3.11.5
  demo/vl-select.html
  dist/style.css
  dist/vl-select.js
  dist/vl-select.src.js
  package-lock.json
  package.json
  src/style.css
  src/vl-select.js
  test/e2e/components/vl-select.js
  test/e2e/pages/vl-select.page.js
  test/unit/vl-select.test.html
Labels: chore

#121 Value setter wordt weer correct aangeroepen bij een native select
  dist/vl-select.js
  dist/vl-select.min.js
  dist/vl-select.src.js
  src/vl-select.js
  test/unit/vl-select.test.html
Labels: bug

#129 Arrow icon correct tonen bij niet dressed varianten
  demo/vl-select.html
  package-lock.json
  package.json
  src/style.css
Labels: bug
